// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "comparison" section.

import React from 'react';
import FeaturesComparison from '@/components/sections/features/FeaturesComparison';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ComparisonSection(): React.JSX.Element {
  return (
    <div id="comparison" data-section="comparison">
            <SectionErrorBoundary name="comparison">
              <FeaturesComparison
                tag="Advanced Comparison"
                title="Why Choose Future Watt?"
                description="Standard energy solutions vs. Future Watt intelligent infrastructure."
                negativeItems={["High latency monitoring", "Manual scaling overhead", "Fragmented legacy systems"]}
                positiveItems={["Real-time predictive analytics", "Zero-touch automated scaling", "Unified intelligent grid ecosystem"]}
                textAnimation="slide-up"
              />
            </SectionErrorBoundary>
          </div>
  );
}
