// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
            <SectionErrorBoundary name="contact">
              <ContactCta
                tag="Ready to Start?"
                text="Join the energy revolution and scale your sustainability impact today."
                primaryButton={{ text: "Contact Sales", href: "mailto:hello@fwatt.ai" }}
                secondaryButton={{ text: "View Documentation", href: "#" }}
                textAnimation="slide-up"
              />
            </SectionErrorBoundary>
          </div>
  );
}
