// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsFeatureCards from '@/components/sections/metrics/MetricsFeatureCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
            <SectionErrorBoundary name="metrics">
              <MetricsFeatureCards
                tag="Proven Impact"
                title="Performance at Scale"
                description="Data that defines our commitment to reliability."
                metrics={[
                  { value: "99.9%", title: "Grid Reliability", features: ["Predictive uptime", "Self-healing circuits"] },
                  { value: "40%", title: "Efficiency Gain", features: ["Reduced load stress", "Optimized routing"] },
                  { value: "12M+", title: "KWh Managed", features: ["Sustainable sources", "Peak performance"] },
                ]}
                textAnimation="fade"
              />
            </SectionErrorBoundary>
          </div>
  );
}
