// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "social-proof" section.

import React from 'react';
import SocialProofMarquee from '@/components/sections/social-proof/SocialProofMarquee';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function SocialProofSection(): React.JSX.Element {
  return (
    <div id="social-proof" data-section="social-proof">
            <SectionErrorBoundary name="social-proof">
              <SocialProofMarquee
                tag="Our Network"
                title="Powered by Innovation"
                description="Collaborating with global pioneers."
                names={["TerraCorp", "GridInnovators", "EcoEnergy", "NextVolt", "SolarAlliance", "PureGrid", "SustainableFutures"]}
                textAnimation="fade-blur"
              />
            </SectionErrorBoundary>
          </div>
  );
}
