// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "solutions" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function SolutionsSection(): React.JSX.Element {
  return (
    <div id="solutions" data-section="solutions">
            <SectionErrorBoundary name="solutions">
              <FeaturesRevealCardsBento
                tag="Technology"
                title="Our Core Innovations"
                description="Proprietary tech that scales your sustainability infrastructure."
                items={[
                  { title: "Cell Tech", description: "High density energy cells.", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/3d-environment-project-scene_23-2148896042.jpg" },
                  { title: "Grid Dashboard", description: "Real-time management.", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/technology-concept-with-futuristic-element_23-2151910928.jpg" },
                  { title: "Solar Array", description: "Next gen capture.", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/close-up-environment-project_23-2148894106.jpg?_wi=2" },
                  { title: "Wind Capture", description: "Optimized turbine tech.", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/wind-turbines-by-highway-eco-travel-scenic-infrastructure_169016-68028.jpg?_wi=2" },
                  { title: "Storage Units", description: "Modular power banks.", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/technology-background-texture_23-2148105476.jpg" },
                  { title: "Transmission", description: "High performance lines.", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/high-angle-hard-drive-with-red-light-still-life_23-2149417035.jpg" },
                  { title: "Smart Grid", description: "AI driven distribution.", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/african-american-industrial-designer-works-prototypes-creative-studio_482257-124242.jpg" },
                ]}
                textAnimation="fade-blur"
              />
            </SectionErrorBoundary>
          </div>
  );
}
