// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialOverlayCards from '@/components/sections/testimonial/TestimonialOverlayCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
            <SectionErrorBoundary name="testimonials">
              <TestimonialOverlayCards
                tag="Client Stories"
                title="Voices of the New Grid"
                description="Trusted by leaders in sustainability and industrial innovation."
                testimonials={[
                  { name: "Dr. Sarah Chen", role: "Head of Engineering", company: "EcoSystems", rating: 5, imageSrc: "http://img.b2bpic.net/free-photo/confident-attractive-asian-businesswoman-looking-camera-head-shot-portrait_1163-4734.jpg" },
                  { name: "Michael Roberts", role: "CTO", company: "SolarPulse", rating: 5, imageSrc: "http://img.b2bpic.net/free-photo/proud-businessman-with-his-company_1098-2864.jpg" },
                  { name: "Elena Martinez", role: "Operations", company: "GridDirect", rating: 5, imageSrc: "http://img.b2bpic.net/free-photo/african-american-male-professional-works-desk-corporation_482257-122689.jpg?_wi=2" },
                  { name: "David Okafor", role: "Architect", company: "TerraBuild", rating: 5, imageSrc: "http://img.b2bpic.net/free-photo/wind-farms-fields_23-2149154408.jpg" },
                  { name: "Jessica Lee", role: "PM", company: "NextGen", rating: 5, imageSrc: "http://img.b2bpic.net/free-photo/portrait-smiling-businessman-sitting-desk-table-business-company-office_482257-16773.jpg" },
                ]}
                textAnimation="slide-up"
              />
            </SectionErrorBoundary>
          </div>
  );
}
